export const InputDetails ={
    userUpDetails: [
        {
            id: 2,
            name: 'hoten',
            lable: 'Họ và tên',
            type: 'text',
            placeholder: 'Họ và tên',
            required: true,
            //pattern: '^[A-Za-z0-9]{3,12}$',
            //errorMsg: 'Username should be 3-12 characters & should not include any special character!',
        },
        {
            id: 3,
            name: 'sdt',
            lable: 'Số điện thoại',
            type: 'text',
            placeholder: 'Số điện thoại',
            required: true,
            //pattern: '^[A-Za-z]{1,20}$',
            //errorMsg: 'Name is required!',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            required: true,
            //errorMsg: 'Enter a valid email!',
        },
        {
            id: 6,
            name: 'diachi',
            lable: 'Address',
            type: 'text',
            placeholder: 'Address',
            required: true,
            //errorMsg: 'Address is required!',
        },
        {
            id: 7,
            name: 'ngaysinh',
            lable: 'Ngày Sinh',
            type: 'text',
            placeholder: 'Ngày sinh',
            required: true,
            //errorMsg: 'Address is required!',
        },
    ],
    userInpDetails: [
        {
            id: 2,
            name: 'hoten',
            lable: 'Họ và tên',
            type: 'text',
            placeholder: 'Họ và tên',
            required: true,
            pattern: '^[A-Za-z0-9]{3,12}$',
            errorMsg: 'Vui lòng nhập đầy đủ họ tên',
        },
        {
            id: 3,
            name: 'sdt',
            lable: 'Số điện thoại',
            type: 'text',
            placeholder: 'Số điện thoại',
            required: true,
            pattern: '^[A-Za-z]{1,20}$',
            errorMsg: 'Vui lòng nhập sđt',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            required: true,
            errorMsg: 'Vui lòng nhập email hợp lệ!',
        },
        {
            id: 5,
            name: 'password',
            lable: 'Password',
            type: 'password',
            placeholder: 'Password',
            required: true,
            pattern: '^(?=.*[0-9])(?=.*[A-Za-z])(?=.*[!@#$%^&*()_+])[A-Za-z0-9!@#$%^&*()_+]{6,20}$',
            errorMsg:
                'Vui lòng nhập mật khẩu từ 6 đến 12 kí tự !',
        },
        {
            id: 6,
            name: 'diachi',
            lable: 'Địa chỉ',
            type: 'text',
            placeholder: 'Address',
            required: true,
            errorMsg: 'Vui lòng nhập địa chỉ!',
        },
        {
            id: 7,
            name: 'ngaysinh',
            lable: 'Ngày Sinh',
            type: 'text',
            placeholder: 'Ngày sinh',
            required: true,
            errorMsg: 'Vui lòng nhập ngày sinh!',
        },
    ],
    orderInpDetails: [
        {
            id: 2,
            name: 'madh',
            lable: 'Mã đơn hàng',
            type: 'text',
            placeholder: '',
        },
        {
            id: 3,
            name: 'makh',
            lable: 'Mã khách hàng',
            type: 'text',
            placeholder: '',
        },
        {
            id: 4,
            name: 'tongtrigia',
            lable: 'Tổng trị giá',
            type: 'number',
            placeholder: 0,
        },
    ],
    employeeUpDetails: [
        {
            id: 2,
            name: 'hoten',
            lable: 'Tên',
            type: 'text',
            placeholder: '',
            required: true,
            pattern: '^[A-Za-z0-9]{3,12}$',
            errorMsg: 'Username should be 3-12 characters & should not include any special character!',
        },
        {
            id: 3,
            name: 'sdt',
            lable: 'SDT',
            type: 'text',
            placeholder: 'số điện thoại',
            required: true,
            pattern: '^[A-Za-z]{1,20}$',
            errorMsg: 'Name is required!',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            required: true,
            errorMsg: 'Enter a valid email!',
        },
        {
            id: 6,
            name: 'role',
            lable: 'Chức vụ',
            type: 'text',
            placeholder: 'role',
            required: true,
            errorMsg: 'Address is required!',
        },

    ],
    employeeInpDetails: [
        {
            id: 2,
            name: 'hoten',
            lable: 'Tên',
            type: 'text',
            placeholder: 'tên',
            required: true,
            //pattern: '^[A-Za-z0-9]{3,12}$',
            //errorMsg: 'Username should be 3-12 characters & should not include any special character!',
        },
        {
            id: 3,
            name: 'sdt',
            lable: 'SDT',
            type: 'text',
            placeholder: 'sdt',
            //required: true,
            //pattern: '^[A-Za-z]{1,20}$',
            //errorMsg: 'Name is required!',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            //required: true,
            //errorMsg: 'Enter a valid email!',
        },
        {
            id: 5,
            name: 'password',
            lable: 'Password',
            type: 'password',
            placeholder: 'Password',
            //required: true,
            //pattern: '^(?=.*[0-9])(?=.*[A-Za-z])(?=.*[!@#$%^&*()_+])[A-Za-z0-9!@#$%^&*()_+]{6,20}$',
            errorMsg:
                'Password should be 6-20 characters and include at last 1 num, 1 letter, 1 special character!',
        },
        {
            id: 6,
            name: 'role',
            lable: 'Chức vụ',
            type: 'text',
            placeholder: 'role',
            //required: true,
            //errorMsg: 'Address is required!',
        },
        
    ],
    productInpDetails : [
        {
            id: 2,
            name: 'tensanpham',
            lable: 'Tên Sản Phẩm',
            type: 'text',
            placeholder: 'Product title',
            required: false,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 3,
            name: 'loaisanpham',
            lable: 'Loại Sản Phẩm',
            type: 'text',
            placeholder: 'Product description',
            required: false,
            errorMsg: 'Description is required!',
        },
        {
            id: 4,
            name: 'hinh',
            lable: 'Hình',
            type: 'text',
            placeholder: 'Product category',
            required: false,
            errorMsg: 'Category is required!',
        },
        {
            id: 5,
            name: 'gia',
            lable: 'Giá',
            type: 'number',
            placeholder: 'Product price',
            required: false,
            errorMsg: 'Price is required!',
        },
        {
            id: 6,
            name: 'rom',
            lable: 'ROM',
            type: 'text',
            placeholder: 'ROM',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 7,
            name: 'mausac',
            lable: 'Màu sắc',
            type: 'text',
            placeholder: 'Màu sắc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 8,
            name: 'ram',
            lable: 'Ram',
            type: 'number',
            placeholder: 'Ram',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 9,
            name: 'chip',
            lable: 'Chip',
            type: 'text',
            placeholder: 'Chip',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 10,
            name: 'baomat',
            lable: 'Bảo mật',
            type: 'text',
            placeholder: 'Bảo mật',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 11,
            name: 'chongnuoc',
            lable: 'Chông nước',
            type: 'text',
            placeholder: 'Chống nước',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 12,
            name: 'sac',
            lable: 'Sạc',
            type: 'text',
            placeholder: 'Sạc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 13,
            name: 'dophangiai',
            lable: 'Độ Phân Giải',
            type: 'text',
            placeholder: 'Độ Phân Giải',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 14,
            name: 'kichthuoc',
            lable: 'Kích thước',
            type: 'text',
            placeholder: 'Kích thước',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 15,
            name: 'camera',
            lable: 'Camera',
            type: 'text',
            placeholder: 'Camera',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 16,
            name: 'khoiluong',
            lable: 'Khối lượng',
            type: 'text',
            placeholder: 'Khối lượng',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 17,
            name: 'hedieuhanh',
            lable: 'Hệ điều hành',
            type: 'text',
            placeholder: 'Hệ điều hành',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 18,
            name: 'nguongoc',
            lable: 'Nguồn gốc',
            type: 'text',
            placeholder: 'Nguồn gốc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 19,
            name: 'chatlieu',
            lable: 'Chất liệu',
            type: 'text',
            placeholder: 'Chất liệu',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 20,
            name: 'kichthuocmanhinh',
            lable: 'Kích thước màn hình',
            type: 'text',
            placeholder: 'Kích thước màn hình',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 21,
            name: 'loaiphukien',
            lable: 'Loại phụ kiện',
            type: 'text',
            placeholder: 'Loại phụ kiện',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 22,
            name: 'congnghe',
            lable: 'Công Nghệ',
            type: 'text',
            placeholder: 'Công nghệ',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 23,
            name: 'congsuat',
            lable: 'Công Suất',
            type: 'text',
            placeholder: 'Công Suất',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 24,
            name: 'baohanh',
            lable: 'Bảo Hành',
            type: 'text',
            placeholder: 'Bảo Hành',
            required: false,
            errorMsg: 'This field is required!',
        },
    ],
    blogInputs: [
        {
            id: 1,
            name: 'title',
            lable: 'Title',
            type: 'text',
            placeholder: 'Blog title',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 2,
            name: 'description',
            lable: 'Description',
            type: 'text',
            placeholder: 'Blog description',
            required: true,
            errorMsg: 'Description is required!',
        },
        {
            id: 3,
            name: 'tags',
            lable: 'Tags',
            type: 'text',
            placeholder: 'Travel, Communication',
            required: true,
            errorMsg: 'Tag is required!',
        },
    ],
    promotionInputs: [
        {
            id: 2,
            name: 'apdung',
            lable: 'Mức áp dụng',
            type: 'number',
            placeholder: 'Mức áp dụng',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 3,
            name: 'phantramkm',
            lable: 'Phần trăm khuyến mãi',
            type: 'number',
            placeholder: 'Phần trăm khuyến mãi',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 4,
            name: 'batdau',
            lable: 'Thời gian bắt đầu',
            type: 'text',
            placeholder: 'Thời gian bắt đầu',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 5,
            name: 'ketthuc',
            lable: 'Thời gian kết thúc',
            type: 'text',
            placeholder: 'Thời gian kết thúc',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 6,
            name: 'title',
            lable: 'Tiêu đề',
            type: 'text',
            placeholder: 'Tiêu đề khuyến mãi',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 7,
            name: 'image',
            lable: 'Hình ảnh',
            type: 'text',
            placeholder: 'Hình ảnh',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 8,
            name: 'description',
            lable: 'Mô tả',
            type: 'text',
            placeholder: 'Mô tả',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 9,
            name: 'dateSource',
            lable: 'Ngày tạo',
            type: 'text',
            placeholder: 'Ngày tạo',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 10,
            name: 'detail',
            lable: 'Chi tiết',
            type: 'text',
            placeholder: 'Chi tiết',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 11,
            name: 'category',
            lable: 'Phân loại',
            type: 'text',
            placeholder: 'Khuyến mãi',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
    ],
    storeInputs: [
        {
            id: 2,
            name: 'name',
            lable: 'Tên cửa hàng',
            type: 'text',
            placeholder: 'Tên cửa hàng',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 3,
            name: 'provinceCode',
            lable: 'Mã tỉnh',
            type: 'number',
            placeholder: 'Mã tỉnh',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 4,
            name: 'districtCode',
            lable: 'Mã quận/huyện',
            type: 'number',
            placeholder: 'Mã quận/huyện',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
    ],
    guaranteeInputs: [
        {
            id: 2,
            name: 'mota',
            lable: 'Mô tả',
            type: 'text',
            placeholder: 'Mô tả',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 3,
            name: 'tinhtrangbaohanh',
            lable: 'Tình trạng bảo hành',
            type: 'text',
            placeholder: 'Tình trạng bảo hành',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        },
        {
            id: 4,
            name: 'ngbaohanh',
            lable: 'Ngày bảo hành',
            type: 'text',
            placeholder: 'Ngày bảo hành',
            required: true,
            errorMsg: 'Vui lòng nhập trường này!',
        }
    ],
    invoiceInputs: [
        {
            id: 2,
            name: 'makh',
            lable: 'Mã khách hàng',
            type: 'text',
            placeholder: 'Mã khách hàng',
            required: false,
            errorMsg: 'Makh is required!',
        },
        {
            id: 3,
            name: 'manv',
            lable: 'Mã nhân viên',
            type: 'text',
            placeholder: 'Mã nhân viên',
            required: false,
            errorMsg: 'manv is required!',
        },
        {
            id: 4,
            name: 'ngayxuathd',
            lable: 'Ngày xuất hóa đơn',
            type: 'text',
            placeholder: 'Ngày xuất hóa đơn',
            required: false,
            errorMsg: 'ngayxuathd is required!',
        },
        {
            id: 5,
            name: 'tinhtrang',
            lable: 'Tình trạng',
            type: 'text',
            placeholder: 'Tình trạng',
            required: false,
            errorMsg: 'tinhtrang is required!',
        },
        {
            id: 6,
            name: 'trigia',
            lable: 'Giá',
            type: 'number',
            placeholder: 'Trị giá',
            required: false,
            errorMsg: 'Price is required!',
        },
        {
            id: 7,
            name: 'diachigiaohang',
            lable: 'Địa chỉ giao hàng',
            type: 'text',
            placeholder: 'Địa chỉ giao hàng',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 8,
            name: 'phuongthucthanhtoan',
            lable: 'Phương thức thanh toán',
            type: 'text',
            placeholder: 'Phương thức thanh toán',
            required: false,
            errorMsg: 'This field is required!',
        },
    ]
}